version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./frontend/vite_fast:/app
    ports:
      - "5173:5173"
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    working_dir: /app
    tty: true
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - ./api/django_api:/app
